### ISSUE TITLE
Fix the wiki link to point to the wiki

### ISSUE THREAD

**Issue by dahacouk** [bitmindco/ovn-space#1]
It would be great to get http://wiki.ovn.space pointing to the correct place. If you are having trouble getting the wiki under that subdomain then could a simple redirect work in the short term – just so it doesn't point to a 404? Cheers!

**Comment by dahacouk** [comment]
Just to be clear there are two links to the wiki. One works and one doesn't:

![ovn_space___network_of_networks](https://cloud.githubusercontent.com/assets/201752/10635571/9d1b74e6-77f1-11e5-824d-9ff6be07147f.png)

**Comment by dgrmunch** [comment]
Done!
